name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger deployments from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-action@v1
        with:
          flyctl_version: latest
          
      - name: Authenticate with Fly.io
        run: flyctl auth token ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        run: flyctl deploy --app <your-fly-app-name>
